import colors from './../../style/colors'

const style = {
    fullScreen: {
        width: '100vw',
        height: '100vh',
        position: 'absolute',
        top: '0',
    },
    title : {
        width: '100vw',
        textAlign: 'center',
        position: 'absolute',
        color: colors.MidGreen,
        top: 0,
    },
    instructions : {
        marginLeft: '5vw',
        marginBottom: '5vh',
        marginTop: '100px',
        height: '20vh',
        width: '90vw',
        textAlign: 'center',
        fontSize: '18px',
    },
    list : {
        backgroundColor: 'white',
        height:'40vh',
        width: '80vw',
        marginLeft: '10vw',
        borderTop: '5px solid',
        borderLeft: '5px solid',
        borderColor: colors.MidGray,
        borderRadius: '7px',
        position: 'absolute',
        overflow: 'auto',
    },
    waitingCan : {
        marginTop: '35%',
        textAlign: 'center',
        verticalAlign: 'middle',
        display: 'block',
        fontSize: '30px',
    },
    button : {
        position: 'absolute',
        fontSize: '27px',
        width: '60vw',
        height: '7vh',
        bottom: '5vh',
        marginTop: '10vh',
        marginLeft: '20vw',
        backgroundColor: colors.MidGreen,
        borderTopLeftRadius: '50px',
        borderBottomLeftRadius: '50px',
        borderTopRightRadius: '50px',
        borderBottomRightRadius: '50px',
        border: 'none',
        fontWeight: 'bold',
        color: 'white',
    },
    table : {
        width: '100%',
        maxHeight: '40vh',
        backgroundColor: colors.LightGray,
        borderCollapse: 'collapse',
    },
    tr : {
        height: '45px',
        width: '100%',
        borderBottom: '2px solid',
    },
    tdLeft : {
        width: '15%',
        height: '45px',
    },
    tdMiddle : {
        width: '70%',
        height: '45px',
        bold: 'True',
        fontSize: '22.5px',
        fontWeight: 'bold',
    },
    tdRight : {
        width: '15%',
        height: '45px',
        borderLeft: '0',
    },
    checkCircle: {
        fontSize: '45px',
    },
    smashedCan: {
        height: '45px',
    },
    popupAnotherUser : {
        position: 'absolute',
        top: '50vh',
        left: '10vw',
        width: '80vw',
        height: '50vw',
        marginTop: '-25vw',
        border: "solid 2px",
        backgroundColor: colors.LightGray,
        borderRadius: '2%',
        zIndex: 1,
        p : {
            fontSize: '20px',
            padding: '0 10% 0 10%',
            textAlign: 'center',
        },
        button : {
            fontSize: '25px',
            width: '80%',
            height: '25%',
            marginLeft: '10%',
            backgroundColor: colors.MidGreen,
            borderTopLeftRadius: '50px',
            borderBottomLeftRadius: '50px',
            borderTopRightRadius: '50px',
            borderBottomRightRadius: '50px',
            border: 'none',
            fontWeight: 'bold',
            color: 'white',
        }
    },
    opaqueScreen: {
        width: '100vw',
        height: '100vh',
        position: 'absolute',
        top: 0,
        zIndex: 1,
        backgroundColor: 'white',
        opacity: '0.5',
    }
}

export default style;